channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >=3.6
  - snakemake =5.14
  - pyyaml
  - yaml
  - pandas
  - pytest
  - shmlast
  - click
  - khmer >=2.0
  # these are for dag printing
  #- graphviz
  #- networkx
  #- pygments
  #- pygraphviz
  #- psutil
