site_name: dammit
site_url: http://dib-lab.github.io/dammit
repo_name: dammit
repo_url: https://github.com/dib-lab/dammit
edit_uri: ""

extra_css: css/custom.css

copyright: 'Copyright &copy; 2018 <a href="http://ivory.idyll.org/lab/">Lab for Data Intensive Biology</a> at UC Davis'

# change directory names here
docs_dir: doc
site_dir: site

theme:

  # the next 2 lines are required to use the DIB version
  name: null
  custom_dir: 'mkdocs-material-dib/material'

  # pretty colors! see https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
  palette:
    primary: 'green'
    accent: 'purple'
  
  # fun logos! see https://material.io/icons/
  logo:
    icon: 'dns'

  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# this will add docs/css/custom.css to all your docs
extra_css:
  - css/custom.css

# give a title for each page
nav:
  - 'Home': 'index.md'
  - 'Background and Motivations': 'about.md'
  - 'Installation': 'install.md'
  - 'Quickstart: run sample data': quickstart.md
  - 'Annotation Databases and Pipelines': 
    - 'About the Databases': 'database-about.md'
    - 'Annotation Pipelines': 'pipelines.md'

  - 'Dammit Components': 
    - 'Components': dammit-components.md
    - 'Databases': 'database-usage.md'
    - 'Annotate': 'annotate.md'
    
  #- 'Full Tutorial': 'tutorial.md'

  - 'Advanced Usage and Configuration':
    - 'Tool-Specific Configuration': 'configuration.md'
    - 'Distributing dammit jobs on a Cluster': cluster.md
    - 'Advanced Database Setup': 'database-advanced.md'
    - 'Parsing Dammit Results': 'results-parsing.md'
    
  - 'For developers':
    - 'Notes for developers': 'dev_notes.md'
